language: ruby
rvm:
- 1.9.3
- 2.2.3
sudo: required
dist: trusty
env:
  global:
  - FORMATS=human,json
  - HUMAN_OUTPUT=tmp/system_info.txt
  - JSON_OUTPUT=tmp/system_info.json 
  - COOKBOOKS_MASTER_URL="https://api.github.com/repos/travis-ci/travis-cookbooks/git/refs/heads/master"
  - COVERAGE=1
  matrix:
  - COMMANDS_FILE=lib/system_info/commands.yml
  - COMMANDS_FILE=lib/system_info/mini_commands.yml
before_script:
- export COOKBOOKS_SHA=$(curl -s "$COOKBOOKS_MASTER_URL" | jq -r '.object.sha[0:7]')
- mkdir -p ~/bin tmp
script:
- bundle exec rubocop
- bundle exec exe/system-info help report
- bundle exec rspec
- cat tmp/system_info.txt
- jq . < tmp/system_info.json
after_success:
- if [[ "x$COMMANDS_FILE" = "xlib/system_info/commands.yml" &&
        "x$TRAVIS_BRANCH" = "xmaster" &&
        "x$TRAVIS_PULL_REQUEST" = "xfalse" &&
        "x$TRAVIS_RUBY" = "x2.2.3" &&
        "x$(lsb_release -sc)" = "xtrusty" ]] ; then
    unset PRERELEASE_SUFFIX ;
  else
    export PRERELEASE_SUFFIX=pre${TRAVIS_JOB_NUMBER} ;
  fi
- mkdir -p build
- gem build system-info.gemspec
- mv -v $(find . -maxdepth 1 -name '*.gem') build/
addons:
  artifacts:
    paths:
    - build/
    target_paths:
    - '/'
