language: ruby
rvm:
- 1.9.3
- 2.2.3
sudo: required
env:
  global:
  - FORMATS=human,json
  - HUMAN_OUTPUT=tmp/system_info.txt
  - JSON_OUTPUT=tmp/system_info.json 
  - COOKBOOKS_MASTER_URL="https://api.github.com/repos/travis-ci/travis-cookbooks/git/refs/heads/master"
  - COVERAGE=1
  matrix:
  - COMMANDS_FILE=lib/system_info/commands.yml
  - COMMANDS_FILE=lib/system_info/mini_commands.yml
before_script:
- export COOKBOOKS_SHA=$(curl -s "$COOKBOOKS_MASTER_URL" | jq -r '.object.sha[0:7]')
- mkdir -p ~/bin tmp
script:
- bundle exec rubocop
- bundle exec exe/travis-system-info
- grep -A1 'Cookbooks Version' tmp/system_info.txt
- jq -r '.system_info.cookbooks_version.output' < tmp/system_info.json | grep travis-cookbooks
- cat tmp/system_info.txt
- jq . < tmp/system_info.json
